## Describe Cancer Dependency Map Data

In [1]:
import pathlib
import sys

sys.path.append("../")
from utils import load_utils

In [2]:
# Load depmap data
top_dir = ".."
data_dir = "depmap/data"

depmap_df, depmap_cell_df, depmap_gene_df = load_utils.load_depmap(
    top_dir=top_dir, data_dir=data_dir, load_cell_info=True, load_gene_info=True
)

print(depmap_df.shape)
depmap_df.head(3)

(1086, 17387)

,DepMap_ID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000001,0.094568,0.012519,0.027460,0.025962,0.073412,0.027340,0.020199,0.284733,0.022084,...,0.037449,0.080585,0.034309,0.007142,0.004241,0.082956,0.012000,0.003592,0.012679,0.324623
1,ACH-000004,0.012676,0.049011,0.075933,0.033215,0.013176,0.097497,0.005015,0.153166,0.007358,...,0.038768,0.230569,0.007125,0.021209,0.011203,0.060266,0.128375,0.005911,0.004645,0.042530
2,ACH-000005,0.053957,0.027968,0.010139,0.005448,0.018599,0.081636,0.005457,0.159904,0.050884,...,0.017479,0.274568,0.054525,0.033396,0.033416,0.034712,0.092832,0.012482,0.020843,0.050412

In [3]:
print(depmap_cell_df.shape)
depmap_cell_df.head(3)

(1840, 31)

,DepMap_ID,cell_line_name,stripped_cell_line_name,CCLE_Name,alias,COSMICID,sex,source,RRID,WTSI_Master_Cell_ID,...,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,Cellosaurus_NCIt_disease,Cellosaurus_NCIt_id,Cellosaurus_issues,cell_line_clean,tissue
0,ACH-000016,SLR 21,SLR21,SLR21_KIDNEY,NaN,NaN,NaN,Academic lab,CVCL_V607,NaN,...,NaN,NaN,NaN,PT-JnARLB,NaN,Clear cell renal cell carcinoma,C4033,NaN,SLR21,KIDNEY
1,ACH-000032,MHH-CALL-3,MHHCALL3,MHHCALL3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,NaN,Female,DSMZ,CVCL_0089,NaN,...,NaN,NaN,NaN,PT-p2KOyI,NaN,Childhood B acute lymphoblastic leukemia,C9140,NaN,MHHCALL3,HAEMATOPOIETIC_AND_LYMPHOID_TISSUE
2,ACH-000033,NCI-H1819,NCIH1819,NCIH1819_LUNG,NaN,NaN,Female,Academic lab,CVCL_1497,NaN,...,NaN,NaN,NaN,PT-9p1WQv,NaN,Lung adenocarcinoma,C3512,NaN,NCIH1819,LUNG

In [4]:
print(depmap_gene_df.shape)
depmap_gene_df.head(3)

(17386, 3)

  depmap_column_name gene_symbol  ncbi_entrez_id
0           A1BG (1)        A1BG               1
1       A1CF (29974)        A1CF           29974
2            A2M (2)         A2M               2

In [5]:
# How many tissues
depmap_cell_df.tissue.value_counts()

tissue
HAEMATOPOIETIC_AND_LYMPHOID_TISSUE    285
LUNG                                  244
SKIN                                  113
CENTRAL_NERVOUS_SYSTEM                110
BREAST                                 87
LARGE_INTESTINE                        81
UPPER_AERODIGESTIVE_TRACT              78
BONE                                   77
SOFT_TISSUE                            75
OVARY                                  74
PANCREAS                               59
KIDNEY                                 58
AUTONOMIC_GANGLIA                      49
STOMACH                                48
BILIARY_TRACT                          43
MATCHED_NORMAL_TISSUE                  39
FIBROBLAST                             39
OESOPHAGUS                             38
URINARY_TRACT                          38
ENDOMETRIUM                            37
PLEURA                                 32
LIVER                                  28
THYROID                                22
CERVIX                                 21
PROSTATE                               14
ENGINEERED                             11
UVEA                                    8
TESTIS                                  4
PLACENTA                                3
COLON                                   3
SALIVARY_GLAND                          2
SKIN_FV1_RESISTANT                      2
VULVA                                   2
SKIN_CJ1_RESISTANT                      2
SMALL_INTESTINE                         2
SKIN_CJ3_RESISTANT                      1
SKIN_CJ2_RESISTANT                      1
SKIN_FV3_RESISTANT                      1
SKIN_FV2_RESISTANT                      1
PRIMARY                                 1
EYE                                     1
MPNST                                   1
Osteosarcoma                            1
Melanoma_Skin                           1
Melanoma_Eye                            1
ADRENAL_CORTEX                          1
Brain                                   1
Name: count, dtype: int64

In [6]:
# What are the diseases
print(depmap_cell_df.Cellosaurus_NCIt_disease.nunique())
depmap_cell_df.Cellosaurus_NCIt_disease.value_counts().head(20)

256

Cellosaurus_NCIt_disease
Lung adenocarcinoma                         77
Lung small cell carcinoma                   75
Melanoma                                    72
Glioblastoma                                58
Colon adenocarcinoma                        48
Bladder carcinoma                           36
Neuroblastoma                               36
Lung squamous cell carcinoma                35
Ewing sarcoma                               33
Plasma cell myeloma                         31
Esophageal squamous cell carcinoma          28
Tongue squamous cell carcinoma              28
Pancreatic ductal adenocarcinoma            27
Adult acute myeloid leukemia                27
Breast carcinoma                            27
Renal cell carcinoma                        25
Clear cell renal cell carcinoma             25
Intrahepatic cholangiocarcinoma             25
Pancreatic adenocarcinoma                   23
High grade ovarian serous adenocarcinoma    23
Name: count, dtype: int64

In [7]:
# What are the sex distribution
depmap_cell_df.sex.value_counts()

sex
Male      991
Female    747
Name: count, dtype: int64